### ISSUE TITLE
rabbit-manager queue:listen queuename   it not  work!

### ISSUE THREAD

**Issue by ltanme** [kontoulis/rabbit-manager#1]
PHP Warning:  require(/Library/WebServer/Documents/rabbit-manager/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php): failed to open stream: No such file or directory in /Library/WebServer/Documents/rabbit-manager/vendor/composer/autoload_real.php on line 54
PHP Fatal error:  require(): Failed opening required '/Library/WebServer/Documents/rabbit-manager/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php' (include_path='.:') in /Library/WebServer/Documents/rabbit-manager/vendor/composer/autoload_real.php on line 54

please  help me

**Comment by ltanme** [comment]
I use laravel 5.1

**Comment by kontoulis** [comment]
As far as I can see from the error, it has nothing to do with rabbit-manager. It seems you are missing the hamcrest-php package. Run `composer update` and let me know if it resolved your issue.

**Comment by winfan** [comment]
@kontoulis  this, I run composer update! now it work, 
  but I don't know use use "Illuminate\Database\Connectors\MySqlConnector"
PHP Fatal error:  Class 'Illuminate\Database\Connectors\MySqlConnector' not found in /Library/WebServer/Documents/rabbit-manager/src/Handlers/DefaultHandler.php on line 30 
in /Library/WebServer/Documents/rabbit-manager/src/Handlers/DefaultHandler.php

**Comment by ltanme** [comment]
thanks @kontoulis
